In [3]:
import numpy as np
# Oddiy ro'yxat: har bir elementga alohida amal kerak
# royxat = [1, 2, 3, 4, 5]
# natija = [x * 2 for x in royxat]   # tsikl kerak
# natija
# NumPy: butun massivga bir vaqtda amal
massiv = np.array([1, 2, 3, 4, 5])
natija = massiv * 2                # tsiklsiz!
print(natija)   # [ 2  4  6  8 10]

[ 2  4  6  8 10]


In [ ]:
import numpy as np

# # Ro'yxatdan massiv
# a = np.array([1, 2, 3, 4])
# print(type(a))          # [1 2 3 4]

# # 2 o'lchamli massiv (matritsa)
# b = np.array([[1, 2, 3], [4, 5, 6]])
# print(b)
# # [[1 2 3]
# #  [4 5 6]]

# Tayyor massivlar
# nol = np.zeros((2, 3))       # nollar bilan
# print(nol)
# [[0. 0. 0.]
#  [0. 0. 0.]]

# bir = np.ones((2, 2))        # birlar bilan
# print(bir)
# [[1. 1.]
#  [1. 1.]]

# Ketma-ket sonlar (range kabi)
# c = np.arange(0, 10, 2)      # 0 dan 10 gacha, 2 qadam
# print(c)          # [0 2 4 6 8]

# Teng oraliqli sonlar
# d = np.linspace(0, 1, 5)     # 0 dan 1 gacha 5 ta son
# print(d)          # [0.   0.25 0.5  0.75 1.  ]

[0.   0.25 0.5  0.75 1.  ]


In [14]:
massiv = np.array([[1, 2, 3], [4, 5, 6]])

# print(massiv.shape)   # (2, 3)  -> 2 qator, 3 ustun
# print(massiv.ndim)    # 2       -> o'lchamlar soni
# print(massiv.size)    # 6       -> jami elementlar
print(massiv.dtype)   # int64   -> ma'lumot turi

int64


In [17]:
a = np.array([10, 20, 30, 40, 50])

# # Bitta element
# print(a[0])      # 10
# print(a[-1])     # 50 (oxirgi)

# # Kesish (slicing)
# print(a[1:4])    # [20 30 40]
# print(a[:3])     # [10 20 30]
# print(a[2:])     # [30 40 50]

# 2 o'lchamli massivda
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 1])   # 2  -> 0-qator, 1-ustun
print(b[1])      # [4 5 6]  -> butun qator
print(b[:, 0])   # [1 4 7]  -> butun ustun (0-ustun)

2
[4 5 6]
[1 4 7]


In [19]:
a = np.array([5, 12, 8, 20, 3, 15])

# 10 dan katta sonlar
# print(a[a > 10])    # [12 20 15]

# Shartni almashtirish
a[a < 10] = 0
print(a)   # [ 0 12  0 20  0 15]

[ 0 12  0 20  0 15]


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# # Elementlar bo'yicha amallar
# # print(a + b)     # [11 22 33 44]
# # print(b - a)     # [ 9 18 27 36]
# print(a * 2)     # [2 4 6 8]
# print(a ** 2)    # [ 1  4  9 16]

# # # Bitta son bilan (broadcasting)
# print(a + 100)   # [101 102 103 104]

[101 102 103 104]


In [27]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# print(A + B)         # elementlar bo'yicha qo'shish
# # [[ 6  8]
# #  [10 12]]

# print(A @ B)         # matritsa ko'paytmasi (matrix multiplication)
# [[19 22]
#  [43 50]]

print(A.T)           # transponirlash (qator <-> ustun)
# [[1 3]
#  [2 4]]

[[1 3]
 [2 4]]


In [ ]:
a = np.array([4, 8, 15, 16, 23, 42])

# print(a.sum())     # 108  -> yig'indi
# print(a.mean())    # 18.0 -> o'rtacha
# print(a.max())     # 42   -> eng katta
# print(a.min())     # 4    -> eng kichik
# print(a.std())     # standart chetlanish

12.315302134607444


In [34]:
a = np.arange(1, 13)     # 1 dan 12 gacha
# print(a)   # [ 1  2  3  4  5  6  7  8  9 10 11 12]

b = a.reshape(3, 4)      # 3 qator, 4 ustun qilib
print(b)
# # [[ 1  2  3  4]
# #  [ 5  6  7  8]
# #  [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
b = np.array([[1, 2, 3], [4, 5, 6]])
# print(b)

# print(b.sum(axis=0))   # [5 7 9]   -> ustunlar bo'yicha
print(b.sum(axis=1))   # [6 15]    -> qatorlar bo'yicha

[ 6 15]
